name: carbcalc_ua
description: CarbCalc UA — щоденник харчування та калькулятор вуглеводів.
publish_to: "none"
version: 0.6.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  mobile_scanner: ^7.4.0
  http: ^1.6.0
  file_picker: ^10.3.3
  csv: ^6.0.0
  syncfusion_flutter_pdf: ^31.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/products.json
